# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.10-slim

# set workdir
WORKDIR /app

# copy source
COPY . /app

# install dependencies
RUN pip install --no-cache-dir requests beautifulsoup4 mcp lxml

# expose nothing (stdio)

# default command
ENTRYPOINT ["python", "stepstone_server.py"]

